sudo: false

notifications:
  email: false

git:
  depth: 1

language: c

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Install stack as above
  # ...
  # Configure stack to use the system GHC installation
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.0.1/bin:$PATH

install:
  - stack --skip-ghc-check setup

script:
  - stack --skip-ghc-check test

cache:
  directories:
  - $HOME/.stack