sudo: false

notifications:
  email: false

git:
  depth: 1

language: c

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --skip-ghc-check setup

script:
  - stack --skip-ghc-check test

cache:
  directories:
    - $HOME/.stack
